apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 80
